apiVersion: v1
kind: Service
metadata:
  name: tricentis-service
  labels:
    app: nginx
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: tricentis-ingress
spec:
  rules:
  - http:
      paths:
        - path: /nginx/?(.*)
          backend:
            serviceName: nginx-service
            servicePort: 8080
---           
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tricentis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: qasymphony/nginx
        name: tricentis
        ports:
        - containerPort: 8080
          name: tricentis