apiVersion: v1
kind: Service
metadata:
  name: tricentis-service
  labels:
    app: tomcat
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: tomcat
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tricentis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tricentis-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
    spec:
      containers:
      - image: tomcat:latest
        name: tricentis
        ports:
        - containerPort: 80
          name: tricentis
        volumeMounts:
        - name: tricentis-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: tricentis-persistent-storage
        persistentVolumeClaim:
          claimName: tricentis-pv-claim
