apiVersion: v1
kind: Service
metadata:
  name: tricentis-service
  labels:
    app: tomcat
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat
  type: LoadBalancer
 ---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: tricentis-ingress
spec:
  rules:
  - http:
      paths:
        - path: /tomcat/?(.*)
          backend:
            serviceName: tomcat-service
            servicePort: 8080
 ---           
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tricentis-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: qasymphony/tomcat
        name: tricentis
        ports:
        - containerPort: 8080
          name: tricentis