apiVersion: v1
kind: Service
metadata:
  name: tricentis-postgres
  labels:
    app: tomcat
spec:
  ports:
    - port: 5432
      nodePort: 30432
  type: NodePort
  selector:
    app: tomcat
    tier: postgres
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: myefs/aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
  labels:
    app: tomcat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tricentis-postgres
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tomcat
        tier: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: efs-postgres