apiVersion: v1
kind: Service
metadata:
  name: pgadmin-postgres
  labels:
    app: pgadmin
spec:
  ports:
    - port: 5432
      nodePort: 30432
  type: NodePort
  selector:
    app: pgadmin
    tier: postgres---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pgadmin-postgres
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin
        tier: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_DB
          value: postgresdb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pwd
              key: mypwd
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: efs-postgres