apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  ports:
    - port: 80
  selector:
    app: pgadmin
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin
        tier: frontend
    spec:
      containers:
      - image: dpage/pgadmin4
        name: pgadmin
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin"
        - name: PGADMIN_PORT
          value: "80"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pwd
              key: pgadmin-pass
        ports:
        - containerPort: 80
          name: pgadminport