apiVersion: kustomize.config.k8s.io/v1beta1
kind: KustomizationsecretGenerator: 
  - name: postgres-pwd
    literals:
      - mypwd=redhat
      - pgadmin-pass=redhat
resources:
    - my-efs-provisioner.yml
    - my-storage.yml
    - deploy-postgres.yml
    - deploy-postgresadmin.yml