kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: myefs/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
         storage: 10Gi